# Generated by Django 6.0.3 on 2026-03-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('mercado', models.CharField(max_length=100, verbose_name='Mercado')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Conceitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratacao', models.FloatField(verbose_name='Contratação')),
                ('venda', models.FloatField(verbose_name='Venda')),
                ('margem', models.FloatField(verbose_name='Margem')),
                ('margem_percentual', models.FloatField(verbose_name='Margem Percentual')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos', to='core.projeto')),
            ],
            options={
                'verbose_name': 'Conceito',
                'verbose_name_plural': 'Conceitos',
            },
        ),
    ]
