# Generated by Django 6.0.3 on 2026-03-05 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessamentoXLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_processamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Processamento')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('mes_fechado', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mês Fechado')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Processamento XLS',
                'verbose_name_plural': 'Processamentos XLS',
                'ordering': ['-data_processamento'],
            },
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['codigo'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='projeto',
            name='regiao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel_comercial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsável Comercial'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_solucao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Solução'),
        ),
        migrations.CreateModel(
            name='ConceitoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceito', models.CharField(choices=[('carteira_operativa', 'Carteira Operativa'), ('contratacion', 'Contratación'), ('ingresos', 'Ingresos'), ('coste', 'Coste'), ('margen', 'Margen'), ('margen_percentual', 'Margen(%)'), ('clientes', 'Clientes'), ('dpf', 'DPF'), ('alo', 'ALO'), ('existencias', 'Existencias'), ('mov_existencias', 'Mov. Existencias'), ('facturacion', 'Facturación'), ('cobros', 'Cobros'), ('costes_directos_corporativos', 'Costes directos corporativos'), ('costes_directos_auxiliares', 'Costes Directos Auxiliares'), ('costes_elab_ofertas', 'Costes Elab. De Ofertas'), ('disponibilidad', 'Disponibilidad'), ('actividades_id', 'Actividades I+D'), ('desviacion_tasa', 'Desviación Tasa'), ('margen_directo', 'Margen Directo'), ('margen_directo_percentual', 'Margen Directo (%)')], max_length=50, verbose_name='Conceito')),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('valor_realizado', models.FloatField(default=0, verbose_name='Valor Realizado')),
                ('valor_planejado', models.FloatField(default=0, verbose_name='Valor Planejado (POA)')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos_mensais', to='core.projeto')),
                ('processamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceitos_mensais', to='core.processamentoxls')),
            ],
            options={
                'verbose_name': 'Conceito Mensal',
                'verbose_name_plural': 'Conceitos Mensais',
                'ordering': ['projeto', 'mes', 'conceito'],
                'unique_together': {('projeto', 'processamento', 'conceito', 'mes')},
            },
        ),
        migrations.DeleteModel(
            name='Conceitos',
        ),
    ]
