# Generated by Django 6.0.3 on 2026-03-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_processamentoxls_mes_fechado'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='contratacion_poa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Contratação POA'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='contratacion_ytd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Contratação YTD'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ingresos_poa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos POA'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ingresos_ytd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos YTD'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Projeto Ativo'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='is_pipeline',
            field=models.BooleanField(default=False, verbose_name='Projeto Pipeline'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='margen_percentual_ytd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margem % YTD'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='margen_poa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Margem POA'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='margen_ytd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Margem YTD'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='ultimo_processamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.processamentoxls', verbose_name='Último Processamento'),
        ),
    ]
